[theme]
primaryColor = "#00d4ff"
backgroundColor = "#0e0e1c"
secondaryBackgroundColor = "#161630"
textColor = "#e0e0ee"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
